server:
  port: 8091
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: debug

spring:
  application:
    name: demo
    description: Demo reactive
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
app:
  security:
    auth-endpoint: http://127.0.0.1:8090/api/security/v1/validate